### ISSUE TITLE
🛠️ Roadmap

### ISSUE THREAD

**Issue by struckchure** [Overal-X/formatio.storm#2]
# Features
- [ ] File caching for workflows
- [ ] Share variables between jobs and steps
- [x] Read YAML configuration similar to GitHub workflow
- [x] CLI to send workflow to machines
- [x] Agent to execute workflows
- [x] Machine inventory
- [ ] Execute commands as sudo user
- [x] Provide inventory to store sudo user password
- [x] Provide inventory to store ssh user password
- [x] Support for ssh key authentication
- [ ] Usage documentation for cli
- [ ] Usage documentation for code
- [ ] Server group support in inventory
- [ ] Hide sensitive information from logs
